# Generated by Django 5.0.6 on 2024-06-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbie_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbie',
            old_name='is_backlight',
            new_name='sold',
        ),
    ]
